<a href="https://colab.research.google.com/github/sonpn82/Tensor-flow-Developer-Certification-Exam/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using ft.function ( a way to speed up your regular python functions)
* Using GPUs with Tensor flow (or TPUs)
* Exercises to try for yourself!

##Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.8.2


In [5]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of that vector
vector.ndim

1

In [10]:
# Create a matrix (has more than 1 dim)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], 
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16)  # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [15]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [17]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction 
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional arrays of numbers (n can be any number)

## Creating tensors with tf.Variable

In [3]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [4]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [5]:
# Let's try change one of the elements in our changeable tensor

In [6]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [7]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [9]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

* **Note**: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

## Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [20]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [24]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim
not_shuffled

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [25]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [40]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

In [43]:
# Without seed setting, result is different each time
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.803156], shape=(1,), dtype=float32)
tf.Tensor([0.95831835], shape=(1,), dtype=float32)


In [46]:
# With global seed sets, result is same. But if close program and run again, it changes.
tf.random.set_seed(24)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.10927987], shape=(1,), dtype=float32)
tf.Tensor([0.8875979], shape=(1,), dtype=float32)


In [50]:
ran1 = tf.random.Generator.from_seed(33)
ran1 = ran1.normal(shape=(2,3))
ran1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.1589871 ,  1.302304  ,  0.9592239 ],
       [ 0.85874265, -1.5181769 ,  1.4020647 ]], dtype=float32)>

In [55]:
tf.random.shuffle(ran1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.85874265, -1.5181769 ,  1.4020647 ],
       [-0.1589871 ,  1.302304  ,  0.9592239 ]], dtype=float32)>

In [57]:
tf.random.shuffle(ran1, seed=3)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.85874265, -1.5181769 ,  1.4020647 ],
       [-0.1589871 ,  1.302304  ,  0.9592239 ]], dtype=float32)>

In [59]:
ran2 = tf.random.Generator.from_seed(100)
ran2 = ran2.uniform(shape=(3,4))
ran2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.6661966 , 0.7469058 , 0.8769325 , 0.8477416 ],
       [0.22709787, 0.49256873, 0.7682668 , 0.8009803 ],
       [0.7784879 , 0.7249299 , 0.89754343, 0.7963594 ]], dtype=float32)>

In [61]:
tf.random.shuffle(ran2)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.22709787, 0.49256873, 0.7682668 , 0.8009803 ],
       [0.6661966 , 0.7469058 , 0.8769325 , 0.8477416 ],
       [0.7784879 , 0.7249299 , 0.89754343, 0.7963594 ]], dtype=float32)>

In [64]:
ran3 = tf.random.Generator.from_seed(200)
ran3 = ran3.normal(shape = (2,2))
ran3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.83051693,  1.543791  ],
       [-0.5432179 ,  0.36891136]], dtype=float32)>

In [65]:
tf.random.shuffle(ran3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.83051693,  1.543791  ],
       [-0.5432179 ,  0.36891136]], dtype=float32)>

In [66]:
ran4 = tf.random.Generator.from_seed(400)
ran4 = ran4.uniform(shape = (4,4))
ran4

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.34529388, 0.2566265 , 0.6553159 , 0.44317663],
       [0.37663794, 0.29438877, 0.55747545, 0.79740036],
       [0.9539219 , 0.45098853, 0.84633136, 0.18867064],
       [0.41195655, 0.05685592, 0.93212044, 0.10755014]], dtype=float32)>

In [67]:
tf.random.shuffle(ran4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.34529388, 0.2566265 , 0.6553159 , 0.44317663],
       [0.41195655, 0.05685592, 0.93212044, 0.10755014],
       [0.37663794, 0.29438877, 0.55747545, 0.79740036],
       [0.9539219 , 0.45098853, 0.84633136, 0.18867064]], dtype=float32)>

In [68]:
ran5 = tf.random.Generator.from_seed(500)
ran5 = ran5.uniform(shape = (5,5))
ran5

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.63157904, 0.38214397, 0.8704549 , 0.5169318 , 0.69938076],
       [0.5050386 , 0.43766642, 0.8667455 , 0.16113937, 0.67500424],
       [0.8560462 , 0.48929954, 0.97561824, 0.5725883 , 0.8036673 ],
       [0.3923154 , 0.4012767 , 0.25327802, 0.7235824 , 0.51754737],
       [0.32620752, 0.09840012, 0.3233775 , 0.9681879 , 0.29591775]],
      dtype=float32)>

In [69]:
tf.random.shuffle(ran5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.32620752, 0.09840012, 0.3233775 , 0.9681879 , 0.29591775],
       [0.3923154 , 0.4012767 , 0.25327802, 0.7235824 , 0.51754737],
       [0.5050386 , 0.43766642, 0.8667455 , 0.16113937, 0.67500424],
       [0.63157904, 0.38214397, 0.8704549 , 0.5169318 , 0.69938076],
       [0.8560462 , 0.48929954, 0.97561824, 0.5725883 , 0.8036673 ]],
      dtype=float32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:
> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

### Other way to make tensors

In [70]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [71]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing).


In [73]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A


# X = tf.constant(some matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [77]:
A = tf.constant(numpy_A, shape=(3,8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Gettting information from tensors

When dealing with tensors you probaly want to be aware of the following attributes:

* Shape
* Rank
* Axis or dimension
* Size

In [78]:
# Create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [79]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [80]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [84]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists

In [86]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [85]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [88]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [89]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [90]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7], 
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [91]:
# Get the last item ot each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [92]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [95]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [97]:
# Expand the 0 axis
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [100]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [101]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [102]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [103]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [104]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [107]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [108]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [109]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [110]:
tensor.shape

TensorShape([2, 2])

In [120]:
# Create a tensor (3,2) tensor
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
# Create another one
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

# Try matrix multiplication
X @ Y

InvalidArgumentError: ignored

**Resource:** Info and example of matrix multiplication: https://mathsisfun.com/algebra

In [113]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [114]:
# Try to multiply again
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [116]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [122]:
# Change X shape instead
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [123]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [124]:
# Can do the same with transpose
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [126]:
# Try matrix multiplication with tranpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [127]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [128]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [129]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [130]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")  # \n is for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [131]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will tranpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication

### Changing the datatype of tensor

In [135]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [133]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [137]:
# Change from float32 to float16 (reduce precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [139]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E.dtype

tf.float32

In [144]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregrating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [3]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [4]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [39]:
# Create a random tensor with values from 0 to 20
A = np.random.randint(0,100,size=20)
E = tf.constant(A, shape=(2,10))
print(E)
tf.size(E), E.shape, E.ndim

tf.Tensor(
[[22 29  7 67 99 85 53 92 93 93]
 [13 71 34  7 36  3 85 35 89 83]], shape=(2, 10), dtype=int64)


(<tf.Tensor: shape=(), dtype=int32, numpy=20>, TensorShape([2, 10]), 2)

In [40]:
# Get the minimum
print("All min = ", tf.reduce_min(E).numpy())
print("Dim 0 min = ", tf.reduce_min(E,0))
print("Dim 1 min = ",tf.reduce_min(E,1))

All min =  3
Dim 0 min =  tf.Tensor([13 29  7  7 36  3 53 35 89 83], shape=(10,), dtype=int64)
Dim 1 min =  tf.Tensor([7 3], shape=(2,), dtype=int64)


In [41]:
# Get the maximum
print("All max = ", tf.reduce_max(E).numpy())
print("Dim 0 max = ", tf.reduce_max(E,0))
print("Dim 1 max = ",tf.reduce_max(E,1))

All max =  99
Dim 0 max =  tf.Tensor([22 71 34 67 99 85 85 92 93 93], shape=(10,), dtype=int64)
Dim 1 max =  tf.Tensor([99 89], shape=(2,), dtype=int64)


In [42]:
# Get the mean
print("All mean = ", tf.reduce_mean(E).numpy())
print("Dim 0 mean = ", tf.reduce_mean(E,0))
print("Dim 1 mean = ",tf.reduce_mean(E,1))

All mean =  54
Dim 0 mean =  tf.Tensor([17 50 20 37 67 44 69 63 91 88], shape=(10,), dtype=int64)
Dim 1 mean =  tf.Tensor([64 45], shape=(2,), dtype=int64)


In [43]:
# Get the sum
print("All sum = ", tf.reduce_sum(E).numpy())
print("Dim 0 sum = ", tf.reduce_sum(E,0))
print("Dim 1 sum = ",tf.reduce_sum(E,1))

All sum =  1096
Dim 0 sum =  tf.Tensor([ 35 100  41  74 135  88 138 127 182 176], shape=(10,), dtype=int64)
Dim 1 sum =  tf.Tensor([640 456], shape=(2,), dtype=int64)


**Exercise** With that we've just learned, find the variance and standard deviation of our `E` tensor using Tensorflow methods

In [49]:
# Get the std
F = tf.cast(E, dtype=tf.float32)
print("All std = ", tf.math.reduce_std(F))
print("Dim 0 std = ", tf.math.reduce_std(F,0))
print("Dim 1 std = ", tf.math.reduce_std(F,1))

All std =  tf.Tensor(33.45086, shape=(), dtype=float32)
Dim 0 std =  tf.Tensor(
[ 4.4999995 21.        13.5       29.999998  31.500002  41.
 15.999999  28.5        2.         5.       ], shape=(10,), dtype=float32)
Dim 1 std =  tf.Tensor([32.4037  31.91614], shape=(2,), dtype=float32)


In [51]:
# Get the variance
print("All variance = ", tf.math.reduce_variance(F))
print("Dim 0 variance = ", tf.math.reduce_variance(F,0))
print("Dim 1 variance = ", tf.math.reduce_variance(F,1))

All variance =  tf.Tensor(1118.9601, shape=(), dtype=float32)
Dim 0 variance =  tf.Tensor(
[  20.25  441.    182.25  900.    992.25 1681.    256.    812.25    4.
   25.  ], shape=(10,), dtype=float32)
Dim 1 variance =  tf.Tensor([1050.   1018.64], shape=(2,), dtype=float32)


In [55]:
# Using tensorflow_probability 
import tensorflow_probability as tfp
print("Variance = ", tfp.stats.variance(F))
print("Std = ", tfp.stats.stddev(F))


Variance =  tf.Tensor(
[  20.25  441.    182.25  900.    992.25 1681.    256.    812.25    4.
   25.  ], shape=(10,), dtype=float32)
Std =  tf.Tensor(
[ 4.4999995 21.        13.5       29.999998  31.500002  41.
 15.999999  28.5        2.         5.       ], shape=(10,), dtype=float32)


### Find the positional maximum and minimum

In [3]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(24)
F = tf.random.uniform(shape=[10])
F

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.10927987, 0.26020873, 0.7633631 , 0.9664098 , 0.6704161 ,
       0.5704179 , 0.11284781, 0.3750646 , 0.65140796, 0.25983608],
      dtype=float32)>

In [4]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [5]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9664098>

In [6]:
# Find the max value of F 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9664098>

In [7]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [8]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [10]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.10927987>

### Squeezing a tensor (removing all single dimensions)

In [14]:
# Create a tensor to get started
tf.random.set_seed(24)
G = tf.constant(tf.random.uniform(shape=[20]), shape=(1,1,1,1,20))
G

<tf.Tensor: shape=(1, 1, 1, 1, 20), dtype=float32, numpy=
array([[[[[0.10927987, 0.26020873, 0.7633631 , 0.9664098 , 0.6704161 ,
           0.5704179 , 0.11284781, 0.3750646 , 0.65140796, 0.25983608,
           0.5361136 , 0.03527319, 0.08702004, 0.8614912 , 0.25407887,
           0.92887473, 0.6599686 , 0.14698923, 0.3613621 , 0.9529114 ]]]]],
      dtype=float32)>

In [15]:
G.shape

TensorShape([1, 1, 1, 1, 20])

In [17]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([0.10927987, 0.26020873, 0.7633631 , 0.9664098 , 0.6704161 ,
        0.5704179 , 0.11284781, 0.3750646 , 0.65140796, 0.25983608,
        0.5361136 , 0.03527319, 0.08702004, 0.8614912 , 0.25407887,
        0.92887473, 0.6599686 , 0.14698923, 0.3613621 , 0.9529114 ],
       dtype=float32)>, TensorShape([20]))

### One-hot encoding tensor

In [19]:
# Create a list of indices
some_list = [0,1,2,3] # could be red green blue purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [21]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Ildl", off_value="Ialtd")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Ildl', b'Ialtd', b'Ialtd', b'Ialtd'],
       [b'Ialtd', b'Ildl', b'Ialtd', b'Ialtd'],
       [b'Ialtd', b'Ialtd', b'Ildl', b'Ialtd'],
       [b'Ialtd', b'Ialtd', b'Ialtd', b'Ildl']], dtype=object)>

### Squaring, log, square root

In [23]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [24]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [26]:
# Find the square root (will error if use int type)
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [29]:
# Find the log
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow interacts beautifully with NumPy arrays.

**Note:** One of main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [31]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [32]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [33]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [34]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [35]:
# The default types of each are slighly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Fri Jun 10 05:16:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> **Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible